"""Validate pyveil's compatibility manifest, fixtures, and generated docs.

Fails when the machine-readable protection-surface contract drifts from the
synthetic fixtures or the generated compatibility table. This keeps every
"verified" surface claim backed by a real fixture and a reproducible command.

Checks:

- Required fields, known status vocabulary, and valid public channels.
- Unique surface ids and channels; every fixture referenced exactly once.
- Fixture schema (channel, category, mode) and unique fixture ids.
- No personal absolute paths (home directories) in the manifest or fixtures.
- ISO ``YYYY-MM-DD`` ``last_verified`` dates.
- The generated compatibility table in ``compatibility/README.md`` matches the
  manifest (``--check``), or regenerate it (``--write``).

Usage::

    python scripts/validate_compatibility.py --check
    python scripts/validate_compatibility.py --write
"""

from __future__ import annotations

import argparse
import datetime as dt
import re
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from scripts.compat_harness import (  # noqa: E402
    CHANNEL_VALUES,
    COMPAT_DIR,
    KNOWN_CATEGORIES,
    KNOWN_MODES,
    load_fixtures,
    load_manifest,
)

README_PATH = COMPAT_DIR / "README.md"
TABLE_BEGIN = "<!-- BEGIN compatibility-table (generated by scripts/validate_compatibility.py; do not edit) -->"
TABLE_END = "<!-- END compatibility-table -->"

REQUIRED_SURFACE_FIELDS = (
    "id",
    "display_name",
    "status",
    "channel",
    "install",
    "entrypoint",
    "capabilities",
    "constraints",
    "fixture_ids",
    "verification_command",
    "security_boundary",
    "evidence",
    "last_verified",
)
REQUIRED_FIXTURE_FIELDS = (
    "id",
    "channel",
    "category",
    "mode",
    "description",
    "input",
    "expect_entities",
    "expect_absent",
    "expect_preserved",
)
LIST_SURFACE_FIELDS = ("capabilities", "constraints", "fixture_ids")
PERSONAL_PATH_RE = re.compile(r"(?i)(?:/Users/|/home/[^/\"\s]+|/root/|[A-Za-z]:[\\/]Users[\\/])")
DATE_RE = re.compile(r"^\d{4}-\d{2}-\d{2}$")


def _validate_dates(surface: dict[str, Any], errors: list[str]) -> None:
    value = surface.get("last_verified", "")
    if not (isinstance(value, str) and DATE_RE.match(value)):
        errors.append(f"surface '{surface.get('id')}' has non-ISO last_verified: {value!r}")
        return
    try:
        dt.date.fromisoformat(value)
    except ValueError:
        errors.append(f"surface '{surface.get('id')}' has an invalid date: {value!r}")


def validate(manifest: dict[str, Any], fixtures: dict[str, Any]) -> list[str]:
    errors: list[str] = []
    vocabulary = set(manifest.get("status_vocabulary", []))
    if not vocabulary:
        errors.append("manifest is missing status_vocabulary")

    fixture_list = fixtures["fixtures"]
    fixture_ids = [fixture["id"] for fixture in fixture_list]
    fixture_by_id = {fixture["id"]: fixture for fixture in fixture_list}
    if len(fixture_ids) != len(set(fixture_ids)):
        errors.append("duplicate fixture ids found")

    for fixture in fixture_list:
        fid = fixture.get("id", "<missing>")
        for field in REQUIRED_FIXTURE_FIELDS:
            if field not in fixture:
                errors.append(f"fixture '{fid}' is missing required field '{field}'")
        if fixture.get("channel") not in CHANNEL_VALUES:
            errors.append(f"fixture '{fid}' has unknown channel: {fixture.get('channel')!r}")
        if fixture.get("category") not in KNOWN_CATEGORIES:
            errors.append(f"fixture '{fid}' has unknown category: {fixture.get('category')!r}")
        if fixture.get("mode") not in KNOWN_MODES:
            errors.append(f"fixture '{fid}' has unknown mode: {fixture.get('mode')!r}")

    seen_ids: set[str] = set()
    seen_channels: set[str] = set()
    referenced: list[str] = []
    for surface in manifest["surfaces"]:
        sid = surface.get("id", "<missing>")
        for field in REQUIRED_SURFACE_FIELDS:
            if field not in surface:
                errors.append(f"surface '{sid}' is missing required field '{field}'")
        for field in LIST_SURFACE_FIELDS:
            value = surface.get(field)
            if not isinstance(value, list) or not value:
                errors.append(f"surface '{sid}' field '{field}' must be a non-empty list")
        if surface.get("status") not in vocabulary:
            errors.append(f"surface '{sid}' has unknown status: {surface.get('status')!r}")
        channel = surface.get("channel")
        if channel not in CHANNEL_VALUES:
            errors.append(f"surface '{sid}' has unknown channel: {channel!r}")
        if sid in seen_ids:
            errors.append(f"duplicate surface id: {sid}")
        seen_ids.add(sid)
        if channel in seen_channels:
            errors.append(f"duplicate surface channel: {channel}")
        seen_channels.add(channel)
        for fixture_id in surface.get("fixture_ids", []):
            referenced.append(fixture_id)
            if fixture_id not in fixture_by_id:
                errors.append(f"surface '{sid}' references unknown fixture: {fixture_id}")
        _validate_dates(surface, errors)

    if len(referenced) != len(set(referenced)):
        errors.append("a fixture is referenced by more than one surface")
    orphans = sorted(set(fixture_ids) - set(referenced))
    if orphans:
        errors.append(f"fixtures not referenced by any surface: {', '.join(orphans)}")

    for path in (COMPAT_DIR / "manifest.json", COMPAT_DIR / "fixtures.json"):
        for line_no, line in enumerate(path.read_text(encoding="utf-8").splitlines(), start=1):
            if PERSONAL_PATH_RE.search(line):
                errors.append(f"personal absolute path in {path.name}:{line_no}")

    return errors


def render_table(manifest: dict[str, Any]) -> str:
    lines = [
        "| Surface | Channel | Status | Fixtures | Security boundary |",
        "| --- | --- | --- | --- | --- |",
    ]
    for surface in manifest["surfaces"]:
        fixtures = ", ".join(f"`{fixture_id}`" for fixture_id in surface["fixture_ids"])
        lines.append(
            f"| {surface['display_name']} | `{surface['channel']}` | {surface['status']} "
            f"| {fixtures} | {surface['security_boundary']} |"
        )
    return "\n".join(lines)


def _replace_region(text: str, table: str) -> str:
    block = f"{TABLE_BEGIN}\n\n{table}\n\n{TABLE_END}"
    if TABLE_BEGIN in text and TABLE_END in text:
        pattern = re.compile(re.escape(TABLE_BEGIN) + r".*?" + re.escape(TABLE_END), re.DOTALL)
        return pattern.sub(lambda _match: block, text)
    raise ValueError("compatibility table markers not found in compatibility/README.md")


def check_docs(manifest: dict[str, Any], write: bool) -> list[str]:
    table = render_table(manifest)
    if not README_PATH.exists():
        return [f"missing generated doc: {README_PATH.relative_to(ROOT)}"]
    current = README_PATH.read_text(encoding="utf-8")
    updated = _replace_region(current, table)
    if write:
        if updated != current:
            README_PATH.write_text(updated, encoding="utf-8")
        return []
    if updated != current:
        return ["compatibility table in compatibility/README.md is out of date; run --write"]
    return []


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Validate and compare docs (default)")
    parser.add_argument("--write", action="store_true", help="Regenerate the compatibility table")
    args = parser.parse_args()

    manifest = load_manifest()
    fixtures = load_fixtures()
    errors = validate(manifest, fixtures)
    errors.extend(check_docs(manifest, write=args.write))

    if errors:
        print("compatibility validation failed:")
        for error in errors:
            print(f"  - {error}")
        return 1
    surfaces = len(manifest["surfaces"])
    total_fixtures = len(fixtures["fixtures"])
    action = "regenerated docs and validated" if args.write else "validated"
    print(f"compatibility {action}: {surfaces} surfaces, {total_fixtures} fixtures, no drift")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
